 "#version 330 core\n"
"layout (location = 0) in vec3 aPos;\n"
"layout (location = 1) in vec3 aColor;\n"
//"layout (location = 0) in vec3 aPos;\n"
"layout (location = 1) in vec2 aTexCoord;\n"
"out vec2 TexCoord;\n"
"out vec3 ourColor;\n"
"uniform float _Time;"
"void main()\n"
"{\n"
"   vec3 Cool = vec3(aPos.x + cos(_Time), aPos.y + sin(_Time) , 0)*0.5;  "
"   gl_Position = vec4(aPos + Cool, 1.0);\n"
"   gl_Position = vec4(aPos, 1.0); \n"
" TexCoord = aTexCoord;\n"
"   ourColor = aColor;\n"
"}\0";